### ISSUE TITLE
[PE-D][Tester C] Wrongly accepts invalid email format

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F08-2/tp#244]
![Screenshot 2024-11-08 at 16.43.24.png](https://raw.githubusercontent.com/gavinsoh/ped/main/files/35f39f56-057e-4081-b20c-7666d43fdf5e.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: gavinsoh/ped#3

**Comment by k-hian** [comment]
The email format is an acceptable format based on our email constraint.
