### ISSUE TITLE
[PE-D][Tester A] find age allows some invalid input

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F08-2/tp#299]
![image.png](https://raw.githubusercontent.com/L-rrrr/ped/main/files/95a9a7d6-6a9b-40ac-b987-3225981f453d.png)

When I try to search find a/15-10, it should be an invalid command, because the first number should be smaller than or equal to the second number. However, the command will run and give you nothing as the output.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: L-rrrr/ped#9

**Comment by k-hian** [comment]
While this behaviour is expected, we agree that it is not correct. Either an error message should be shown or the range should still work as intended.
