### ISSUE TITLE
[PE-D][Tester A] find age fails to respond sometimes

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F08-2/tp#303]
![image.png](https://raw.githubusercontent.com/L-rrrr/ped/main/files/9aaf0200-d75f-4049-ae81-c1249ffcb6ae.png)

When I key in "find a/10 10", the interface fails to respond. However, when I key in "find a/10" or "find a/10 15", it will respond as per normal. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: L-rrrr/ped#12

**Comment by k-hian** [comment]
Duplicate of #297
